using UnityEngine;

/// <summary>
/// Represents a room that can be Generated by the Map Generator 
/// </summary>
[RequireComponent(typeof(BoxCollider))]
public class GeneratedRoom : MonoBehaviour
{
    BoxCollider roomCollider;
    #region Initialization
    void Awake()
    {
        roomCollider = GetComponent<BoxCollider>();
    }
    #endregion

    /// <summary>
    /// </summary>
    /// <param name="cellSize">The size of a cell in the map</param>
    /// <returns>The Dimensions of the room using the given cell size as reference.</returns>
    Vector2Int GetDimensions(int cellSize)
    {
        return new Vector2Int(Mathf.CeilToInt(roomCollider.size.x * transform.localScale.x), Mathf.CeilToInt(roomCollider.size.z * transform.localScale.z));
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="cellSize">The size of a cell in the map</param>
    /// <returns>The representation of this room as a Room script. Used for Map Gen</returns>
    public Room GetRoomRepresentation(int cellSize)
    {
        Vector2Int roomDimensions = GetDimensions(cellSize);
        return new Room(roomDimensions.x,roomDimensions.y);
    }
}