@startmindmap Enemy Behaviour Tree
top to bottom direction
*[#FFFFFF] Start
**[#FF5964] E? (Mission)
***[#FFD640] E_Hunt
****[#4083FF] Hunt Down Player
*****[#FF5964] ⟳
******[#FF5964] ->
*******[#7FFA80] Follow Player
*******[#FF5964] ⟳ Player is close?
********[#7FFA80] Attack
***[#FFD640] E_Destroy
****[#4083FF] Destroy Objective
*****[#FF5964] ⟳
******[#FF5964] Player is close?
*******[#FF5964] TRUE
********[#FF5964] ⟳ Player is close?
*********[#FF5964] ->
**********[#7FFA80] Follow Player
**********[#7FFA80] Attack
*******[#FF5964] FALSE
********[#FF5964] ->
*********[#7FFA80] Move Towards Objective
*********[#7FFA80] Attack
@endmindmap